//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int Id { get; set; }
        public string Link1 { get; set; }
        public int Type { get; set; }
        public int StatusCode { get; set; }
        public int RunningInfoId { get; set; }
    
        public virtual RunningInfo RunningInfo { get; set; }
    }
}
